// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SolicitarMunicion_SolicitarM_FullMethodName = "/grpc.SolicitarMunicion/SolicitarM"
)

// SolicitarMunicionClient is the client API for SolicitarMunicion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolicitarMunicionClient interface {
	SolicitarM(ctx context.Context, in *MunitionRequest, opts ...grpc.CallOption) (*MunitionReply, error)
}

type solicitarMunicionClient struct {
	cc grpc.ClientConnInterface
}

func NewSolicitarMunicionClient(cc grpc.ClientConnInterface) SolicitarMunicionClient {
	return &solicitarMunicionClient{cc}
}

func (c *solicitarMunicionClient) SolicitarM(ctx context.Context, in *MunitionRequest, opts ...grpc.CallOption) (*MunitionReply, error) {
	out := new(MunitionReply)
	err := c.cc.Invoke(ctx, SolicitarMunicion_SolicitarM_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolicitarMunicionServer is the server API for SolicitarMunicion service.
// All implementations must embed UnimplementedSolicitarMunicionServer
// for forward compatibility
type SolicitarMunicionServer interface {
	SolicitarM(context.Context, *MunitionRequest) (*MunitionReply, error)
	mustEmbedUnimplementedSolicitarMunicionServer()
}

// UnimplementedSolicitarMunicionServer must be embedded to have forward compatible implementations.
type UnimplementedSolicitarMunicionServer struct {
}

func (UnimplementedSolicitarMunicionServer) SolicitarM(context.Context, *MunitionRequest) (*MunitionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitarM not implemented")
}
func (UnimplementedSolicitarMunicionServer) mustEmbedUnimplementedSolicitarMunicionServer() {}

// UnsafeSolicitarMunicionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolicitarMunicionServer will
// result in compilation errors.
type UnsafeSolicitarMunicionServer interface {
	mustEmbedUnimplementedSolicitarMunicionServer()
}

func RegisterSolicitarMunicionServer(s grpc.ServiceRegistrar, srv SolicitarMunicionServer) {
	s.RegisterService(&SolicitarMunicion_ServiceDesc, srv)
}

func _SolicitarMunicion_SolicitarM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MunitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolicitarMunicionServer).SolicitarM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SolicitarMunicion_SolicitarM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolicitarMunicionServer).SolicitarM(ctx, req.(*MunitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SolicitarMunicion_ServiceDesc is the grpc.ServiceDesc for SolicitarMunicion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SolicitarMunicion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.SolicitarMunicion",
	HandlerType: (*SolicitarMunicionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SolicitarM",
			Handler:    _SolicitarMunicion_SolicitarM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}

const (
	IDEquipo_IdentificarEquipo_FullMethodName = "/grpc.IDEquipo/IdentificarEquipo"
)

// IDEquipoClient is the client API for IDEquipo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IDEquipoClient interface {
	IdentificarEquipo(ctx context.Context, in *IDReply, opts ...grpc.CallOption) (*IDRequest, error)
}

type iDEquipoClient struct {
	cc grpc.ClientConnInterface
}

func NewIDEquipoClient(cc grpc.ClientConnInterface) IDEquipoClient {
	return &iDEquipoClient{cc}
}

func (c *iDEquipoClient) IdentificarEquipo(ctx context.Context, in *IDReply, opts ...grpc.CallOption) (*IDRequest, error) {
	out := new(IDRequest)
	err := c.cc.Invoke(ctx, IDEquipo_IdentificarEquipo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IDEquipoServer is the server API for IDEquipo service.
// All implementations must embed UnimplementedIDEquipoServer
// for forward compatibility
type IDEquipoServer interface {
	IdentificarEquipo(context.Context, *IDReply) (*IDRequest, error)
	mustEmbedUnimplementedIDEquipoServer()
}

// UnimplementedIDEquipoServer must be embedded to have forward compatible implementations.
type UnimplementedIDEquipoServer struct {
}

func (UnimplementedIDEquipoServer) IdentificarEquipo(context.Context, *IDReply) (*IDRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IdentificarEquipo not implemented")
}
func (UnimplementedIDEquipoServer) mustEmbedUnimplementedIDEquipoServer() {}

// UnsafeIDEquipoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IDEquipoServer will
// result in compilation errors.
type UnsafeIDEquipoServer interface {
	mustEmbedUnimplementedIDEquipoServer()
}

func RegisterIDEquipoServer(s grpc.ServiceRegistrar, srv IDEquipoServer) {
	s.RegisterService(&IDEquipo_ServiceDesc, srv)
}

func _IDEquipo_IdentificarEquipo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDEquipoServer).IdentificarEquipo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IDEquipo_IdentificarEquipo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDEquipoServer).IdentificarEquipo(ctx, req.(*IDReply))
	}
	return interceptor(ctx, in, info, handler)
}

// IDEquipo_ServiceDesc is the grpc.ServiceDesc for IDEquipo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IDEquipo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.IDEquipo",
	HandlerType: (*IDEquipoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IdentificarEquipo",
			Handler:    _IDEquipo_IdentificarEquipo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}
