// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SolicitarMunicionClient is the client API for SolicitarMunicion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolicitarMunicionClient interface {
	SolicitarM(ctx context.Context, in *MunitionRequest, opts ...grpc.CallOption) (*MunitionReply, error)
}

type solicitarMunicionClient struct {
	cc grpc.ClientConnInterface
}

func NewSolicitarMunicionClient(cc grpc.ClientConnInterface) SolicitarMunicionClient {
	return &solicitarMunicionClient{cc}
}

func (c *solicitarMunicionClient) SolicitarM(ctx context.Context, in *MunitionRequest, opts ...grpc.CallOption) (*MunitionReply, error) {
	out := new(MunitionReply)
	err := c.cc.Invoke(ctx, "/grpc.SolicitarMunicion/SolicitarM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolicitarMunicionServer is the server API for SolicitarMunicion service.
// All implementations must embed UnimplementedSolicitarMunicionServer
// for forward compatibility
type SolicitarMunicionServer interface {
	SolicitarM(context.Context, *MunitionRequest) (*MunitionReply, error)
	mustEmbedUnimplementedSolicitarMunicionServer()
}

// UnimplementedSolicitarMunicionServer must be embedded to have forward compatible implementations.
type UnimplementedSolicitarMunicionServer struct {
}

func (UnimplementedSolicitarMunicionServer) SolicitarM(context.Context, *MunitionRequest) (*MunitionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitarM not implemented")
}
func (UnimplementedSolicitarMunicionServer) mustEmbedUnimplementedSolicitarMunicionServer() {}

// UnsafeSolicitarMunicionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolicitarMunicionServer will
// result in compilation errors.
type UnsafeSolicitarMunicionServer interface {
	mustEmbedUnimplementedSolicitarMunicionServer()
}

func RegisterSolicitarMunicionServer(s grpc.ServiceRegistrar, srv SolicitarMunicionServer) {
	s.RegisterService(&SolicitarMunicion_ServiceDesc, srv)
}

func _SolicitarMunicion_SolicitarM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MunitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolicitarMunicionServer).SolicitarM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.SolicitarMunicion/SolicitarM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolicitarMunicionServer).SolicitarM(ctx, req.(*MunitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SolicitarMunicion_ServiceDesc is the grpc.ServiceDesc for SolicitarMunicion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SolicitarMunicion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.SolicitarMunicion",
	HandlerType: (*SolicitarMunicionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SolicitarM",
			Handler:    _SolicitarMunicion_SolicitarM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
